### ISSUE TITLE
Banning player adds multiple entrys to the cfg

### ISSUE THREAD

**Issue by SilentSymphony** [rexxar-tc/SEServerExtender#5]
For a long time now everytime i ban someone it has been adding extra entrys to my server config so when i go to /unban someone they are not unbanned and i've had to edit them out manually at restarts.

seems to add about 3 entrys per ban

**Comment by rexxar-tc** [comment]
I think this is related to another issue involving command duplication. Shouldn't be an issue to add a check for duplicate entries in ban lists.

**Comment by rexxar-tc** [comment]
Okay, turns out that the unban command _also_ adds the user to the ban list. Someone goofed and hardcoded a bool to be true rather than respect user input, so the core issue is now fixed.

There also isn't any check to see if the user you're banning is already banned, so I should look into that as well.
